# Should fail gracefully! Should not interrupt devshell init process
import sys
from pathlib import Path

npkgs = len(sys.argv) - 3
DEVDIR = sys.argv[1]
PKGVAR = sys.argv[2]
pkgs = {}
for i in range(3, 3 + npkgs):
    pkgspec = sys.argv[i]
    pkgspecsplit = pkgspec.split(":")
    if pkgspecsplit[1] and "pkg-src" in pkgspecsplit[2:]:
        pkgs[pkgspecsplit[0]] = (pkgspecsplit[1], pkgspecsplit[2:])

if len(pkgs.keys()) == 0:
    exit()

letset = ""
pyinputset = ""
inputset = ""
for pkgname, pkgspec in pkgs.items():
    if "python3" in pkgspec[0]:
        pyinputset += f"\n      {pkgname}"
    else:
        inputset += f"\n    {pkgname}"
    letset += f"\n  {pkgname} = {pkgspec[0]}.override {{"
    letset += f"\n    pkg-src = pkgs.lib.cleanSource ./sources/{pkgname}/.;"
    for dependency in pkgspec[1]:
        if dependency in pkgs.keys():
            letset += f"\n    inherit {dependency};"
    letset += "\n  };"

shell_contents = """
{{ pkgs ? import {0} {{}}}}:
let{1}
in pkgs.mkShell {{
  nativeBuildInputs = [
    (pkgs.python3.withPackages (p: with p; [
      # other python pkgs here{2}
    ])){3}
    pkgs.bashInteractive
  ];
}}
""".format(
    PKGVAR, letset, pyinputset, inputset
)

shell_path = Path(DEVDIR) / "shell.nix"
generated_path = Path(DEVDIR) / ".devshell-generated-shell.nix"


def write_if_changed(path, contents):
    if path.exists() and path.read_text() == contents:
        return
    path.write_text(contents)


if not shell_path.exists():
    write_if_changed(shell_path, shell_contents)
    write_if_changed(generated_path, shell_contents)
elif generated_path.exists() and shell_path.read_text() == generated_path.read_text():
    # The user has not edited the generated shell, so it is safe to reconcile it
    # with the current workspace definition.
    write_if_changed(shell_path, shell_contents)
    write_if_changed(generated_path, shell_contents)
elif shell_path.read_text() == shell_contents:
    # Adopt an unmodified shell generated by an older devshell version. If its
    # contents differ, treat it as user-owned and leave it alone.
    write_if_changed(generated_path, shell_contents)
