name: "Changelog Bot Trigger"

on:
  issue_comment:
    types:
      - edited

jobs:
  process-changelog:
    name: Generate Changelog Entry
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Check if comment has checkbox
        run: |
          python3 .github/extract_description.py "${{ github.event.comment.body }}"
      - name: Update Changelog
        if: success()
        run: |
          git config user.name "goromal (bot)"
          git config user.email "goromal.bot@gmail.com"
          mkdir -p changes
          echo "$CHANGE_DESCRIPTION" > changes/pr-${{ github.event.issue.number }}.md
          git add changes/pr-${{ github.event.issue.number }}.md
          git commit -m "Update changelog"
          git push
