name: Release
on:
  pull_request:
    types:
      - closed

jobs:
  major-release:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'MajorRelease')) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.ANIXBOT_DEPLOY_KEY }}
    - run: |
        git config user.name "Deploy from CI"
        git config user.email ""
        git checkout master
        python scripts/increment_anix.py major
        git add .
        git commit -m "Bump major ANIX_VERSION -> $(cat ANIX_VERSION)"
        git tag v$(cat ANIX_VERSION) HEAD
        git push origin master && git push --tags
  minor-release:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'MinorRelease')) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.ANIXBOT_DEPLOY_KEY }}
    - run: |
        git config user.name "Deploy from CI"
        git config user.email ""
        git checkout master
        python scripts/increment_anix.py minor
        git add .
        git commit -m "Bump minor ANIX_VERSION -> $(cat ANIX_VERSION)"
        git tag v$(cat ANIX_VERSION) HEAD
        git push origin master && git push --tags
  patch-release:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'PatchRelease')) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.ANIXBOT_DEPLOY_KEY }}
    - run: |
        git config user.name "Deploy from CI"
        git config user.email ""
        git checkout master
        python scripts/increment_anix.py patch
        git add .
        git commit -m "Bump patch ANIX_VERSION -> $(cat ANIX_VERSION)"
        git tag v$(cat ANIX_VERSION) HEAD
        git push origin master && git push --tags
