name: Release
on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'Release')) }}
    runs-on: ubuntu-latest
    steps:
    - name: TODO
      run: |
        echo "RELEASE"
